### ISSUE TITLE
IK Question

### ISSUE THREAD

**Issue by Scott216** [mimeindustries/MeArm#3]
I don't have this arm, but I do have a 4-axis arm from Sain Smart which is somewhat similar. My question is, when you move the servo that adjusts the angle between horizontal and bicep (abi), does the angle between the bicep and forearm change, even if you are not moving that servo?  
I'm trying to figure out the kinematics for my arm, but it's hard because if I change abi angle, the afo angle also changes just by the way the arm is designed.  So if I want the afo angle to remain the same, I actually need to move that servo that controls the afo angle as the abi angle changes. I haven't been able to figure out how to do that yet?

**Comment by mithi** [comment]
In my version of the MeArm (also a derivative), the two axes are
independent. I know this because when when I hold one link so that it
resists the movement caused by the other arm, it can independently move
only up and down or forward and backward with out affecting the other. This
is directly because of the measurement of the 4 bar linkages in which the
arm is based. Check if your Saint Smart arm has the same measurements as
the one of the original meArm. I think there is a youtube video (an Indian
guy) which discusses this concept, you might want to search for it. I'll
try to post some pictures later to further illustrate the concept :)

http://mithi.xyz

**Comment by mithi** [comment]
Sorry my bad scratch this comment I was talking about a different arm.

**Comment by mithi** [comment]
Okay here goes the update version of my comment

In my version of the MeArm (also a derivative), the two axes are
independent.
 I know this because when when I hold one link so that it resists the
movement caused by the other link, it can independently move only up and
down or forward and backward with out affecting the other.

*You might mistake that the two axes are dependent because of the following
reasons (I got confused as well initially) *

1. When you change the end effectors position without constraining the
motion of one link, then both servos will move, but this due to the natural
forces acting on them, not because they are dependent. Think of it like a
frictionless pivot vs a pivot with friction.

2. The shape of the parallelogram of each four-bar linkage which each servo
controls changes when you rotate each axes independently even when
constraining  the movement of the other servo. This does not mean they're
the angle of the servo with respect to the "world/fixed frame" or the
horizontal does not change. Try to ignore the four bar linkage and picture
only the link which the servo is directly connected to reinforce this
concept in your mind.

I will post a short video to aid this comment later :)

By the way however if you move it directly horizontal, naturally the the
two independent angles change ( as dictated by the inverse kinematics).
(which means if I constraint one link from moving, and i move the
end-effector directly forward or backward I will feel a resistance tugging
me and wont be able to reach my goal. Careful! Don't force it or your arm
might break!)

I hope I answered your question well :)

http://mithi.xyz

**Comment by Scott216** [comment]
Hi Mithi, 
I think your arm works similar to mine.  Thank you for the videos.  At the start of your video (https://youtu.be/1Q3unEnOJ0E?t=0s), you are holding one servo stationary.  But as you move the arm  the angle between horizontal and the bicep arm change as does the angle between the bicep and forearm.  In the IK formulas I've seen like this one: http://www.oliverjenkins.com/blog/2012/9/inverse-kinematics-and-robot-arms, if you only move one servo, then only that angle changes.  In your arm and my arm, if tell the servo for θ1 to move, θ2 angle will also change even if that servo hasn't changed because the servo is not located at the joint between the bicep (L1) and forearm (L2).  
For example, on my arm, if I start out with  θ1 at 90 degrees and  θ2 also at no degrees.  Then I have the bicep servo move about 45 degrees so the arm moves forward and I tell the forearm servo not to move at all, then the  θ1 angle about 45, but  θ2 is approximately 135 degrees. The IK formulas I've seen assume  θ2 is still at 90 degrees in this example.  
I did a little experimenting and figured out for every degree I move the bicep servo, I need to move the forearm servo at the same time by 1.2 degree if I want to keep θ2 from changing, but this doesn't work for the whole range of motion of the arm.
What IK formulas are you using for your arm?

**Comment by mithi** [comment]
I see what you mean. It's because it's a parallel four-bar linkage.

I didn't really do the inverse kinematics yet, but maybe this quick sketch
might help you.

[image: Inline image 2]

The geometrical relationships from the diagram
*180 = theta2 + (180 - theta1) + theta*
*simplifying you get *
*theta1 = theta2 + theta *

Example

*first position *
theta1 = 90 angle of link1 wrt to the horizontal
theta2 = 45 angle of link 2 wrt to the horizontal
theta = 45 angle between link1 and 2

*2nd position *
we move theta one 45 degrees counter clockwise, as a result:

theta1 = 135 angle of link1 wrt to the horizontal
theta2 = 45 angle of link 2 wrt to the horizontal
theta = 90 angle between link1 and 2

I hope I answered you question.




On Wed, Sep 9, 2015 at 11:04 AM, Scott Goldthwaite <notifications@github.com

**Comment by Scott216** [comment]
Thanks.  I actually just did a similar sketch and it really helped to understand the relationship between the angles.  It turned out to be simpler then I thought.  We'll see if I can get the IK working properly

![arm angles](https://cloud.githubusercontent.com/assets/819693/9763139/e4b9e338-56d5-11e5-8490-f50ff04675b7.jpg)

**Comment by mithi** [comment]
Have you seen  a few  implementations? 
https://github.com/phenoptix/me-arm-ik
also
https://github.com/phenoptix/meArm-1

among a few others. 

I haven't gotten around to look at it in detail yet. But it looks pretty straight forward and the authors gave comments generously

**Comment by Scott216** [comment]
Thanks for the links, I'll check them out.
